project:
  type: website
  output-dir: docs

website:
  title: "marina kochuten"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
#      - href: resources.qmd
#        text: resources
      - href: posts.qmd
        text: my work
  page-footer: 
    background: light
    left: Copyright 2024, Marina Kochuten
    right: This website is built with {{< fa heart title="a solid heart icon" >}} & {{< fa brands github title="the octocat github icon" >}}
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: false
    page-layout: full

editor: visual

