project:
  type: website
  output-dir: docs

website:
  title: "marina kochuten"
  favicon: images/Untitled.png
  navbar:
    title: false
    logo: images/logo-no-background.png
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
#      - href: resources.qmd
#        text: resources
      - href: posts.qmd
        text: my work
#      - href: cv/website-resume.pdf
#        text: cv
  page-footer: 
    background: light
    left: "&copy; 2024 Marina Kochuten"
    right: 
    - icon: linkedin
      href: https://www.linkedin.com/in/marina-kochuten-4786b6324/
      #target: blank
    - icon: github
      href: https://github.com/marinakochuten
      #target: blank
    - icon: envelope
      href: mailto:marinakochuten@bren.ucsb.edu
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: false
    page-layout: full

editor: visual

