project:
  type: website
  output-dir: docs

website:
  title: "Marina Kochuten"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - posts.qmd
  page-footer: 
    background: light
    left: Copyright 2024, Marina Kochuten
    right: This website is built with {{< fa heart title="a solid heart icon" >}} & {{< fa brands github title="the octocat github icon" >}}
format:
  html:
    theme: styles.scss
    mainfont: Montserrat
    toc: false
    page-layout: full

editor: visual

